### ISSUE TITLE
Error with export *

### ISSUE THREAD

**Issue by samcday** [google/traceur-compiler#1042]
With traceur 0.0.42, I get the following error if I try to re-export everything from another dependency (using `export * from "foo"`).

```
TypeError: Cannot call method 'map' of undefined
    at CommonJsModuleTransformer.transformObjectLiteralToDescriptors (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:17187:53)
    at CommonJsModuleTransformer.wrapModule (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:17179:32)
    at CommonJsModuleTransformer.transformModule (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:14944:25)
    at Module.transform (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:4774:26)
    at CommonJsModuleTransformer.transformAny (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:10671:27)
    at FromOptionsTransformer.append (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:21152:55)
    at eval (eval at <anonymous> (/Users/samday/src/confstats-connect/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:20087:16)
```

**Comment by arv** [comment]
Stale.

**Comment by arv** [comment]
The patch is still visible from the bug which is still open.

**Comment by Jonahss** [comment]
Ran into this issue myself. Status a year later?

**Comment by Jonahss** [comment]
:+1: great!
