### ISSUE TITLE
Node.js: relativeRequire is unable to find modules in nested node_modules directories

### ISSUE THREAD

**Issue by skozin** [google/traceur-compiler#1485]
In a clean directory, run:

``` bash
npm install debug
npm install traceur

echo "require('debug'); console.log('ok');" >> index.js
echo "require('traceur').require.makeDefault(); require('debug'); console.log('ok');" >> index-traceur.js
```

This will create a directory structure like this:

``` text
project
 ├ node_modules
 │  ├ traceur
 │  └ debug
 │     ├ node_modules
 │     │  └ ms
 │     └ debug.js
 ├ index.js
 └ index-traceur.js
```

Now run `node index.js`. This will work:

``` text
$ node index.js
ok
```

Run `node index-traceur.js`. This fails on both Node v0.10 and v0.11:

``` text
$ node index-traceur.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.relativeRequire [as require] (/Users/user/project/node_modules/traceur/bin/traceur.js:289:103)
    at require (/Users/user/project/node_modules/debug/debug.js:4:26)
    at Object.<anonymous> (/Users/user/project/node_modules/debug/debug.js:11:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (/Users/user/project/node_modules/traceur/src/node/require.js:65:21)
    at Module.load (module.js:355:32)
```

Inside `project/node_modules/debug/debug.js` there is a `require` of the `ms` package:

``` js
exports.humanize = require('ms');
```

When running without traceur, this `require` call is performed in the context of `project/node_modules/debug/debug.js` module, so the path `project/node_modules/debug/node_modules` is inspected, and the `ms` package is found.

When running with traceur, `relativeRequire('project/node_modules/debug/debug.js', 'ms')` [calls](https://github.com/google/traceur-compiler/blob/master/src/runtime/relativeRequire.js#L42) `require('ms')`, but in the context of `traceur.js` module, which prevents Node.js module loader from finding the require'd package.

**Comment by amechti** [comment]
i have same problem !!!!
this is my server.js:

var io = require('socket.io');
var express = require('express');
var http = require('http');
 
var app =  module.exports.app = express();
//var path = require('path');
var server = http.createServer(app);
//io.listen(server);
//app.configure(function(){
 // app.use(express.static(path.join(__dirname + '/public')));
//});
app.get('/', function(req, res, next){
  res.render('./index.html');
  //res.sendfile(__dirname + '/index.html');
});
server.listen(8080);
console.log(' running at http://localhost:8080/');

 
var socket = io.listen(server, {
  flashPolicyServer: false,
  transports: ['websocket', 'flashsocket', 'htmlfile', 'xhr-multipart', 'xhr-polling', 'jsonp-polling']
});
var allClients = 0;
var clientId = 1;
socket.on('connection', function(client) {
  var my_timer;
  var my_client = { "id": clientId, "obj": client };
  clientId += 1;
  allClients += 1;
  my_timer = setInterval(function () {
    my_client.obj.send(JSON.stringify({ "timestamp": (new Date()).getTime(), "clients": allClients }));
  }, 1000);
  client.on('message', function(data) {
    my_client.obj.broadcast(JSON.stringify({ message: "poke send by client "+my_client.id }));
    console.log(data);
  });
  client.on('disconnect', function() {
    clearTimeout(my_timer);
    allClients -= 1;
    console.log('disconnect');
  });
});
when i run server i get this error 
{Error: Cannot find module 'html'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at new View (C:\Program Files\nodejs\node_modules\express\lib\view.js:50:49)
   at EventEmitter.app.render (C:\Program Files\nodejs\node_modules\express\lib\application.js:545:12)
   at ServerResponse.res.render (C:\Program Files\nodejs\node_modules\express\lib\response.js:938:7)
   at C:\Program Files\nodejs\server send msg\server.js:14:7
   at Layer.handle [as handle_request] (C:\Program Files\nodejs\node_modules\express\lib\router\layer.js:82:5)
   at next (C:\Program Files\nodejs\node_modules\express\lib\router\route.js:110:13) }
please helpe!!!!!!!

**Comment by johnjbarton** [comment]
I don't see any thing in this example that relates to traceur.
