### ISSUE TITLE
No test cases set --outputLanguage=es6. PureES6Transformer fails.

### ISSUE THREAD

**Issue by tbosch** [google/traceur-compiler#1700]
Source:
```
class Test {
  super()
}
```

Transpiled to ES6 with source maps leads to the error:
```
TypeError: Cannot read property 'line' of undefined
    at ParseTreeMapWriter.originate (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22573:26)
    at ParseTreeMapWriter.enterBranch (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22561:12)
    at ParseTreeMapWriter.visitAny (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22532:14)
    at ParseTreeMapWriter.visitExpressionStatement (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:21840:12)
    at ExpressionStatement.visit (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:7570:15)
    at ParseTreeMapWriter.visitAny (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:4161:20)
    at ParseTreeMapWriter.visitAny (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22533:81)
    at ParseTreeMapWriter.writeList_ (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22442:14)
    at ParseTreeMapWriter.writelnList_ (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:22419:14)
    at ParseTreeMapWriter.visitFunctionBody (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:21907:12)
    at FunctionBody.visit (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:7691:15)
    at ParseTreeMapWriter.visitAny (eval at loadModule (/Users/tbosch/projects/angular2/tools/transpiler/index.js:99:19), <anonymous>:4161:20)
```

**Comment by johnjbarton** [comment]
Please list the version number and tell us how you are transpiling.  

The example is a parse error we are not handling well.

**Comment by arv** [comment]
@tbosch Can you provide valid syntax? Your example is not valid ES6.

**Comment by johnjbarton** [comment]
Here is what should happen:
http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--source-maps%20%0Aclass%20Test%20%7B%0A%20%20super()%0A%7D

But I guess you are calling either the command line or API.

**Comment by tbosch** [comment]
Sorry, my bad. Here is the correct example:
```
class Test {
  constructor() {
    super();
  }
}
```

We are using traceur 0.0.82.

Btw, the current master seems to have another problem when using es6 as output language: The `PureES6Transformer` now expects an `options` argument, which is not passed down by `Compiler` when it creates it. See http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--output-language%3Des6%0Aclass%20Test%20%7B%0A%20%20constructor()%20%7B%20%0A%20%20%7D%0A%7D

**Comment by johnjbarton** [comment]
> Btw, the current master seems to have another problem.
Please report separate issues on .... separate issues ;-)

**Comment by johnjbarton** [comment]
Seems like that example works fine:
http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--source-maps%20%0Aclass%20Test%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D

**Comment by tbosch** [comment]
@johnjbarton Yes, but it does not set `output-language=es6` :-)
