### ISSUE TITLE
Async arrows without parens throw an exception in the compiler

### ISSUE THREAD

**Issue by dfreeman** [google/traceur-compiler#1723]
I would expect an arrow of the form `async foo => bar` to parse the same as `async (foo) => bar`, or worst-case to produce a syntax error. Instead, a `TypeError` is thrown during compilation.

```
$ cat in.js
(async foo => bar)

$ traceur --experimental in.js
TypeError: Cannot read property 'type' of undefined
    at FunctionExpression.isGenerator (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:5890:61)
    at needsTransform (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:20176:48)
    at GeneratorTransformPass.transformFunctionExpression (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:20203:12)
    at FunctionExpression.transform (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:6817:26)
    at GeneratorTransformPass.transformAny (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:13129:27)
    at GeneratorTransformPass.transformParenExpression (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:13710:29)
    at ParenExpression.transform (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:7275:26)
    at GeneratorTransformPass.transformAny (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:13129:27)
    at GeneratorTransformPass.transformParenExpression (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:13710:29)
    at ParenExpression.transform (/Users/dfreeman/Desktop/tmp/node_modules/traceur/bin/traceur.js:7275:26)
```

For what it's worth, 6to5 has opted to [treat this as valid syntax](https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&=&code=(async%20foo%20%3D%3E%20bar)).

**Comment by arv** [comment]
This is an internal error.

Someone is passing in undefined... found it... Fixing in a sec.

**Comment by dfreeman** [comment]
Awesome; thanks for the quick turnaround.
