### ISSUE TITLE
make test/unit/util/ broken in master branch

### ISSUE THREAD

**Issue by mnieper** [google/traceur-compiler#1731]
make test/unit/util/

```
$ make test/unit/util/
./traceur test/modular/tests.js

  Error: Error: File not found '/home/mnieper/github/traceur-compiler/test/unit/runtime/test_a.js'
Specified as ./test/unit/runtime/test_a.js.
Imported by /home/mnieper/github/traceur-compiler/.
Normalizes to /home/mnieper/github/traceur-compiler/test/unit/runtime/test_a.js
locate resolved against base '/home/mnieper/github/traceur-compiler/'

    at InternalLoader.handleCodeUnitLoadError (/home/mnieper/github/traceur-compiler/bin/traceur.js:28890:38)
    at /home/mnieper/github/traceur-compiler/bin/traceur.js:28749:18
    at promiseHandle (/home/mnieper/github/traceur-compiler/bin/traceur.js:2209:20)
    at /home/mnieper/github/traceur-compiler/bin/traceur.js:2203:9
    at Object.flush [as _onImmediate] (/home/mnieper/github/traceur-compiler/bin/traceur.js:1968:7)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  476 passing (11s)
  2 failing

  1) SourceMapMapping columnIndexGreaterOrEqual:
     Error: timeout of 2000ms exceeded
      at [object Object].<anonymous> (/home/mnieper/github/traceur-compiler/node_modules/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2) SourceMapMapping testNextPosition:
     Error: timeout of 2000ms exceeded
      at [object Object].<anonymous> (/home/mnieper/github/traceur-compiler/node_modules/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



Makefile:103: recipe for target 'test/unit/util/' failed
make: *** [test/unit/util/] Error 2
```

**Comment by arv** [comment]
I saw this too. There is some old file in there after the commit.

One way that fixed it for me was:

```
git checkout master
rm -rf test/
git reset --hard origin/master
make test
```

This resets the test directory to what it is origin/master.

@johnjbarton

**Comment by arv** [comment]
Oh, look in `.gitignore`. I think that the `.generated.js` files are the real cause. We should probably update the `.gitignore` file to remove stuff that are now causing trouble.

**Comment by johnjbarton** [comment]
Sorry I missed this. If you have open branches that you rebase please delete any `.generated.js` files.  The Makefile should have dealt with them but it didn't and they are gone now....
