### ISSUE TITLE
make test errors

### ISSUE THREAD

**Issue by blakemcbride** [google/traceur-compiler#1769]
Greetings,

I did:

    git clone
    npm install
    make
    make test

All went well except that the `make test` returned:

    1151 passing (5s)
    3 failing

    1) Feature Tests  PromiseAll.js:
       TypeError: invalid_argument
        at Function.all (native)
        at eval (test/feature/PromiseAll.js:25:18)
        at eval (native)
        at LoaderCompiler.evaluateCodeUnit (/home/blake/traceur-compiler.git/bin/traceur.js:29207:36)
        at LoadCodeUnit.evaluate (/home/blake/traceur-compiler.git/bin/traceur.js:29360:34)
        at InternalLoader.evaluate (/home/blake/traceur-compiler.git/bin/traceur.js:29654:29)
        at InternalLoader.handleCodeUnitLoaded (/home/blake/traceur-compiler.git/bin/traceur.js:29567:16)
        at /home/blake/traceur-compiler.git/bin/traceur.js:29435:16

    2) Feature Tests Collections Map.js:
       AssertionError: expected undefined to equal 'value11'
        at eval (test/feature/Collections/Map.js:41:8)
        at eval (native)
        at LoaderCompiler.evaluateCodeUnit (/home/blake/traceur-compiler.git/bin/traceur.js:29207:36)
        at LoadCodeUnit.evaluate (/home/blake/traceur-compiler.git/bin/traceur.js:29360:34)
        at InternalLoader.evaluate (/home/blake/traceur-compiler.git/bin/traceur.js:29654:29)
        at InternalLoader.handleCodeUnitLoaded (/home/blake/traceur-compiler.git/bin/traceur.js:29567:16)
        at /home/blake/traceur-compiler.git/bin/traceur.js:29435:16

    3) Feature Tests Collections Set.js:
       AssertionError: expected false to be true
  
     make: *** [test] Error 3

Is this normal, or did I do something wrong?

Thanks.

Blake

**Comment by johnjbarton** [comment]
All tests should pass...on linux.

What OS.  These fails looks like they may be polyfill collisions.  What version of node?

**Comment by arv** [comment]
This is going to be "fixed" by #1755

These tests fail in the latest stable version of node.js and io.js because V8 had bugs in these two cases.

**Comment by blakemcbride** [comment]
node version 0.12.0

OS 64 bit LinuxMint
