### ISSUE TITLE
Error compiling for-on loop with 'break' body

### ISSUE THREAD

**Issue by vadzim** [google/traceur-compiler#1827]
Traceur 0.0.87 crashes while compiling the code
```Javascript
async function* x() {}

async function y() {
	for ( let a on x() )
		break
}

y()
```
The output is
```
TypeError: Value cannot be converted to an Object
    at Object.checkObjectCoercible (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:299:15)
    at Object.spread (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:1311:43)
    at InnerForOnTransformer.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19520:64)
    at Function.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19634:68)
    at ForOnTransformer.transformForOnStatement_ (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19658:36)
    at ForOnTransformer.transformForOnStatement (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19655:19)
    at ForOnStatement.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:7374:26)
    at ForOnTransformer.transformAny (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:14104:27)
    at ForOnTransformer.transformList (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:14111:32)
    at ForOnTransformer.transformStatements_ (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:15331:40)
```

**Comment by arv** [comment]
Here is the bug:

https://github.com/google/traceur-compiler/blob/master/src/codegeneration/InnerForOnTransformer.js#L81-L82

The transformer always assumes the body is a Block, which it isn't in this case.

@mnieper

**Comment by mnieper** [comment]
I'll take care of it tomorrow.
