### ISSUE TITLE
Tests are failing on Windows

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#1831]

**Comment by arv** [comment]
```sh
./tval test/runUnitTests.js
Error: Error: File not found 'd:\unit\unitTestRunner.js'
Specified as ./unit/unitTestRunner.js.
Imported by d:\Projects\traceur\test\runUnitTests.js.
Normalizes to d:unit/unitTestRunner.js
locate resolved against base 'd:/Projects/traceur/'

    at InternalLoader.handleCodeUnitLoadError (d:\Projects\traceur\bin\traceur.js:30219:38)
    at d:\Projects\traceur\bin\traceur.js:30078:18
    at promiseHandle (d:\Projects\traceur\bin\traceur.js:2278:20)
    at d:\Projects\traceur\bin\traceur.js:2272:9
    at flush (d:\Projects\traceur\bin\traceur.js:2048:7)
    at process._tickCallback (node.js:415:13)
make: *** [test/unit] Error 1
```
