### ISSUE TITLE
Invalid output on await + destructuring in the same statement

### ISSUE THREAD

**Issue by bottleofwater** [google/traceur-compiler#1867]
Hi,

[(demo)](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%20%0Aasync%20function%20test()%20%7B%0A%20%20(await%20foo).map((%5Bx%5D)%3D%3Ex)%3B%0A%7D)
```js
// Options: --async-functions 
async function test() {
  (await foo).map(([x])=>x);
}
```
```
SyntaxError: Unexpected token ?
    at eval (native)
    at LoaderCompiler.evaluateCodeUnit (http://google.github.io/traceur-compiler/bin/traceur.js:29800:36)
    at EvalCodeUnit.evaluate (http://google.github.io/traceur-compiler/bin/traceur.js:29956:34)
    at InternalLoader.evaluate (http://google.github.io/traceur-compiler/bin/traceur.js:30257:29)
    at InternalLoader.handleCodeUnitLoaded (http://google.github.io/traceur-compiler/bin/traceur.js:30170:16)
    at InternalLoader.module (http://google.github.io/traceur-compiler/bin/traceur.js:30056:12)
    at TraceurLoader.module (http://google.github.io/traceur-compiler/bin/traceur.js:30317:35)
    at transcode (http://google.github.io/traceur-compiler/demo/transcode.js:26:10)
    at compileContents (http://google.github.io/traceur-compiler/demo/repl-module.js:148:7)
    at compile (http://google.github.io/traceur-compiler/demo/repl-module.js:118:7)
```

**Comment by arv** [comment]
We are missing parens around the initializer expression in the variable statement.

Take this example:

```js
function f([x]) {
  return x;
}
```

We transform that into:

```js
  function f($__0) {
    var $__2, $__3, $__4, $__5;
    var x = ($__4 = $__0[$traceurRuntime.toProperty(Symbol.iterator)](), ($__5 = $__4.next()).done ? void 0 : $__5.value);
    return x;
  }
```

But when the function is part of an await expression we pass this through the ExplodeExpressionTransformer. We should not traverse into functions.

So to fix this we need to make trannsformFunctionExpression and transformArrowFunction no ops.

**Comment by bottleofwater** [comment]
It seems to work fine on the current REPL, so I'll go ahead and close this issue. Thanks.

**Comment by arv** [comment]
Oh, nice. I guess my last paren fix fixed this too.
