### ISSUE TITLE
Syntax error in export throws in compiler

### ISSUE THREAD

**Issue by johnjbarton** [google/traceur-compiler#2004]
```js
export y = x
```
https://google.github.io/traceur-compiler/demo/repl.html#export%20y%20%3D%20x

```
TypeError: Cannot read property 'visit' of undefined
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitAny (https://google.github.io/traceur-compiler/bin/traceur.js:4844:30)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitExportDeclaration (https://google.github.io/traceur-compiler/bin/traceur.js:4982:14)
    at ExportDeclaration.$__super.visit (https://google.github.io/traceur-compiler/bin/traceur.js:7316:17)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitAny (https://google.github.io/traceur-compiler/bin/traceur.js:4844:31)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitList (https://google.github.io/traceur-compiler/bin/traceur.js:4852:18)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitModule (https://google.github.io/traceur-compiler/bin/traceur.js:5117:14)
    at Module.$__super.visit (https://google.github.io/traceur-compiler/bin/traceur.js:8015:17)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visitAny (https://google.github.io/traceur-compiler/bin/traceur.js:4844:31)
    at ModuleSpecifierVisitor.ParseTreeVisitor.visit (https://google.github.io/traceur-compiler/bin/traceur.js:4847:14)
    at LoaderCompiler.getModuleSpecifiers (https://google.github.io/traceur-compiler/bin/traceur.js:30594:32)
```

**Comment by arv** [comment]
I see.This is invalid syntax but we do not flag it correctly.
