### ISSUE TITLE
Feature test Collections Set.js fails on node 0.10.38

### ISSUE THREAD

**Issue by johnjbarton** [google/traceur-compiler#2024]
1) Feature Tests Collections Set.js:
     AssertionError: expected '[\n  0,\n  42.24,\n  null,\n  {},\n  {\n    "__$127662951$405202073$__": 2813\n  },\n  "keykeykey",\n  null,\n  true,\n  null\n]' to equal '[\n  0,\n  42.24,\n  null,\n  {\n    "__$127662951$405202073$__": 2813\n  },\n  {},\n  "keykeykey",\n  null,\n  true,\n  null\n]'
      at assertArrayEquals (test/asserts.js:31:8)
      at test/feature/Collections/Set.js:60:1
      at NodeLoaderCompiler.evaluateCodeUnit (src/node/NodeLoaderCompiler.js:46:18)
      at LoadCodeUnit.HookedCodeUnit.evaluate (src/runtime/InternalLoader.js:174:30)
      at InternalLoader.evaluate (src/runtime/InternalLoader.js:568:25)
      at InternalLoader.handleCodeUnitLoaded (src/runtime/InternalLoader.js:454:12)
      at loader_.fetch.then.then.then.catch.codeUnit.state (src/runtime/InternalLoader.js:286:9)
      at src/runtime/polyfills/Promise.js:120:56
      at promiseHandle (src/runtime/polyfills/Promise.js:226:18)
      at src/runtime/polyfills/Promise.js:219:7

**Comment by arv** [comment]
Once I fix this we should add more node versions to travis. Testing on 0.10 is good because it lacks WeakMap and Symbol.
