### ISSUE TITLE
Bug: can't extend the native Map/WeakMap/Set/WeakSet class

### ISSUE THREAD

**Issue by stuartZhang** [google/traceur-compiler#2107]
Bug: can't extend the native Map/WeakMap/Set/WeakSet class.
Description: Only the ES 6 classes can't be extended. However, both the traditional built-in classes (e.g. Date) and the custom classes are able to be successfully extended to instantiate a sub class.

Source code:

    class B extends Map{
      get b(){
        return 20;
      }
    }
    const b = new B();
    console.log(b.b);

Run the JavaScript file by:

    $ ../node_modules/.bin/traceur test.js

Runtime Error:

    ModuleEvaluationError: Constructor Set requires 'new'
        at B.Set (native)
        at tailCall (/home/stzhang/var/webapps/connect/main/node_modules/traceur/bin/traceur.js:932:24)
        at Function.apply (/home/stzhang/var/webapps/connect/main/node_modules/traceur/bin/traceur.js:963:20)
        at new B (/home/stzhang/var/webapps/connect/main/unit_tests/mojioApiTokenRetrieval.bbjs:494:43)
        at /home/stzhang/var/webapps/connect/main/unit_tests/mojioApiTokenRetrieval.bbjs:500:11

**Comment by johnjbarton** [comment]
repl test case

https://google.github.io/traceur-compiler/demo/repl.html#class%20B%20extends%20Map%7B%0A%20%20get%20b()%7B%0A%20%20%20%20return%2020%3B%0A%20%20%7D%0A%7D%0Aconst%20b%20%3D%20new%20B()%3B%0Aconsole.log(b.b)%3B

**Comment by stuartZhang** [comment]
I suspect that the below statement throws an error that the "new" operator is required.
    $traceurRuntime.superConstructor(B).apply(this, arguments);

**Comment by stuartZhang** [comment]
Referencing the feedback from the previus issue: https://github.com/google/traceur-compiler/issues/1413, it works as design.

**Comment by arv** [comment]
I wish a knew

**Comment by arv** [comment]
There is a work around:

Compile:

```js
class M extends Map {
  constructor() {
    super();
  }
}
```

to:

```js
class M extends Map {
  constructor() {
    const self = new Map();
    self.__proto__ = M.prototype;  // should really be new.targe.prototype
    return self;
  }
}
```

but there are 2 issues making this hard:

1. Detecting when to do this transformation.
2. It needs `new.target` to work correctly and `new.target` is too expensive to emulate

**Comment by zloirock** [comment]
1. Simple list of built-in constructors by the spec. Isn't perfect, but better solutions will be much harder.
2. `new.target.prototype` -> `Object.getPrototypeOf(this)`

**Comment by arv** [comment]
You cannot touch `this` before calling `super()` in a constructor... but the compiled code is not using a constructor so it seems like it would work.

Another problem would be sub classing `M`... The way we compile constructors doesn't do the right thing when an object is returned.

**Comment by zloirock** [comment]
> but the compiled code is not using a constructor so it seems like it would work.

Sure, it's approach for a compiled code, I use it for a long time.

> Another problem would be sub classing `M`

Here required complete subclassing reform like in `babel@6`.
